name: testapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.2.19
  camera: ^0.10.0+1
  camera_web: ^0.3.3
  cupertino_icons: ^1.0.6
  tflite_v2: ^1.0.0
  path_provider: ^2.0.5
  tflite_flutter: ^0.10.1
  url_launcher: ^6.0.10
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/model_original2.tflite
    - assets/labels.txt
    
  fonts:
    - family: Typefesse
      fonts:
        - asset: assets/fonts/typefesse/Typefesse_Claire-Obscure.otf
        - asset: assets/fonts/typefesse/Typefesse_Pleine.otf
